name: Hilde Geeraert
favicon: null
layout_spectrum: 0.14010252570733428
typography_spectrum: 0.07686743512749672
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.797680240124464
  lightness: 0.9834199878387153
  saturation: 0.16838996158912778
  rhythmicContrast: 0.17525989492423832
purpose: []
